//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sample_webapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int CourseId { get; set; }
        public string Title { get; set; }
        public string Topic { get; set; }
        public string Product { get; set; }
        public string Description { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string rating { get; set; }
    }
}
